version: '3.8'
services:
    chatbot:
        build: ./chatbot
        container_name: virtassist-chatbot
        command: sh -c "python database.py && python main.py && cron"
        env_file:
            - .env.docker
        depends_on:
            - db
            - qa
        networks:
            - db-conn
            - qa-conn
    db:
        build: ./db
        container_name: virtassist-db
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - db-conn
    qa:
        build: ./qa
        container_name: virtassist-qa
        command: sh -c "python database.py && python main.py"
        env_file:
            - .env.docker
        depends_on:
            - db
        networks:
            - db-conn
            - qa-conn

volumes:
    db-data:

networks:
    db-conn:
        driver: bridge
    qa-conn:
        driver: bridge
