FROM python:3.10.0-slim-buster AS db-migrations
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt
COPY schema.py .
COPY create_extension.py .
COPY alembic.ini .
COPY migration migration
